/* === DO NOT EDIT THIS FILE ===
 *
 * This file has been automatically generated. 
 * To update the list of agents rerun make.
 *
 * Stefan Bird <stbird@seatiger.org>, 2004
 */

#include <stdlib.h>
#include "c4.h"

extern double agent_random (Game_state *current_state, int player, int x, int y);
extern double agent_simple (Game_state *current_state, int player, int x, int y);

int count_agents()
{
   return 2;
}

Agent **get_agents()
{
   Agent **funcs = emalloc(sizeof(Agent *) * count_agents());

   funcs[0] = emalloc(sizeof(Agent));
   funcs[0]->agentFunction = agent_random;
   funcs[0]->name = "random";

   funcs[1] = emalloc(sizeof(Agent));
   funcs[1]->agentFunction = agent_simple;
   funcs[1]->name = "simple";

   return funcs;
}
